### PR TITLE
Fix regional language variants not being properly accessed

### PR DESCRIPTION
**Pull request by Tmpod**
I noticed there was a problem when I visited the main project page in incognito, where the recommended instances were not matching those defined for my language (`pt-PT`). Turned out, `recommended_instances.json` only had `pt` and `pt_BR`.

There was another issue, however. The browser reports languages with dashes, while the i18n registry had codes with underscores. I changed the values to comply with browsers, and it all works correctly now.

This is not the ideal fix. It would be better to have some sort of fallback system where it tries to find the best match for the language reported by the browser. So, for example, if I visited the website in `pt-PT` but it didn't have it, it would first try to match the more general language code `pt`, before trying to find another regional variant like `pt-BR`. Something for a later PR though.

### CODE REVIEW

**Review by dessalines — COMMENTED** [review]
Looks good, but remove that instance_stats from this PR.

**Comment by Nutomic** [comment]
A better solution would be to take only the first part of the language string (eg `pt`) and compare that. I dont think it makes sense to distinguish by the full `pt-PT` for now. Anyway merging this.

**Comment by Tmpod** [comment]
I can't seem to be able to read the details on that failed job.

**Comment by Nutomic** [comment]
This time it worked.

**Pull request merged**
