### PR TITLE
Add lemmy.ca as a recommended instance

### PR DESCRIPTION
**Pull request by Sh4d**
We'd like to add lemmy.ca as a recommended instance please!

### CODE REVIEW

**Comment by wiki-me** [comment]
Do we really need to add all those recommended instances?

at least some users expect we will evaluate them well, As long as there is no scoring or methodology to evaluate them and the servers currently recommended are not overloaded maybe we should just keep the existing list , the longer a server exists the bigger are the chances it is good because otherwise we will hear about it.

**Comment by Sh4d** [comment]
> the servers currently recommended are not overloaded 

That doesn't seem like a good enough criteria to me to say we should keep directing users to those servers.

If we end up directing 90% of the lemmy user base to only a handful of instances, isn't that the counter to the point of the fediverse?

I fully support some criteria for what makes a server recommended though!

**Comment by wiki-me** [comment]
> That doesn't seem like a good enough criteria to me to say we should keep directing users to those servers.

> If we end up directing 90% of the lemmy user base to only a handful of instances, isn't that the counter to the point of the fediverse?

My personal opinion is that there is enough diversification, that should not be the primary concern but usability and user experience , But yeah ideally there should be a criteria , something like:
* at least two system administrators, a [bus factor](https://en.wikipedia.org/wiki/Bus_factor) larger then one
* should be general purpose
* should exist for at etleast a year
* more then 1000 monthly active users
* A donation system set up, so if the instance becomes bigger it will be possible to pay for more hardware , something the admins might not want to do if it gets expensive.

It's more work documenting this and somebody gotta do the reviews but if you are just adding instances what is the point of recommending? , Just let the users pick the instance , they can already do that so am not sure playing with the recommended instances really effects decentralization.

Also lemmy.ca is geared towards canadians and not a general purpose instance, so it does not seem like a good fit.

**Review by dessalines — APPROVED** [review]

**Comment by dessalines** [comment]
This is already a big instance, we should do smaller ones. Also in the future we'll probably switch to curating our own list of recommended instances, rather than accepting PRs.

**Pull request closed without merging**
