### PR TITLE
Updated Mlem TestFlight link

### PR DESCRIPTION
**Pull request by JakeShirley**
Mlem dev here.  We had to update our TestFlight link so here is the new one!

### CODE REVIEW

**Comment by BrooklynMan** [comment]
also from the Mlem Team. Please update the testflight link. also, the link to the new github repo is https://github.com/mormaer/Mlem

**Comment by JakeShirley** [comment]
Bumping one more time 😺

**Review by dessalines — CHANGES_REQUESTED** [review]
The github link?

**Comment by JakeShirley** [comment]
Apologies @dessalines.  Just updated the GitHub link.

**Review by Nutomic — APPROVED** [review]

**Pull request merged**
