### PR TITLE
added lemy.lol to recommended-instances.json ✨

### PR DESCRIPTION
**Pull request by ismailkarsli**
I opened the instance about 2 days ago and I want to grow Lemmy fediverse. I will not run away like vlemmy and try to not defederated from beehaw like sh.itjust.works 😀

I think you will reject it due to few users and community at the moment. In that case, I'd appreciate it if you could set a limit for it.

### CODE REVIEW

**Comment by ismailkarsli** [comment]
Me and my 20 users on my instance:
367ACAD0-F7F5-43E5-B2A2-3222F6391FA2

**Comment by ismailkarsli** [comment]
17EF374C-4CC7-4E4A-BC09-AB61FD9A33C9

**Comment by ismailkarsli** [comment]
image

**Review by sharunkumar — APPROVED** [review]
lgtm

**Pull request closed without merging**
