### PR TITLE
add retrolemmy.com to instances-definitions.ts

### PR DESCRIPTION
**Pull request by Die4Ever**

### CODE REVIEW

**Review by SleeplessOne1917 — APPROVED** [review]

**Comment by Die4Ever** [comment]
did something go wrong here? I still don't see retrolemmy.com on https://join-lemmy.org/instances?topic=gaming&language=en&scroll=true

**Comment by dessalines** [comment]
It updates hourly

**Comment by Die4Ever** [comment]
> Edit: actually its probably blocking the crawler for some reason. Either that or no one's connected to its communities yet, so its not in other instances connected list.

it's visible in this list https://lemmy.ml/instances

**Comment by Nutomic** [comment]
The site only shows instances with 5+ monthly users.

https://github.com/LemmyNet/joinlemmy-site/blob/main/crawl.mjs#L67

**Pull request merged**
