### PR TITLE
Autogen instance data

### PR DESCRIPTION
**Pull request by dessalines**

### CODE REVIEW

**Comment by Nutomic** [comment]
So this just takes the list instances crawled, and renders that same list into HTML, right? I think we should do it a bit differently, by adding an allowlist of instances in this repo, and only showing those on the site. Otherwise it would be very easy for eg a fascist instance to sneak in without us noticing. You would run the crawler as `cargo run -- --start-instances *allowlist* --depth 0`

It would also be nice to run the crawler on the server and not at build time, so that the instance list can easily be updated every hour or so.

Also I think that the order of instances should be randomized. Otherwise the largest instances will always be on top and keep growing, while small instances are at the bottom and receive very few new users.

**Comment by dessalines** [comment]
The blocklist is something that should be built into lemmy-stats-crawler, so that it could be used as a command line directive here: https://github.com/LemmyNet/lemmy-instance-stats/blob/main/run.sh

> It would also be nice to run the crawler on the server and not at build time, so that the instance list can easily be updated every hour or so.

It works just like translations now, as a git submodule pointing to `lemmy-instance-stats`, which I'll eventually put in a cronjob on my own machine. I think I'd rather have that data ( `stats.json` ) be statically compiled and bundled into join-lemmy, rather than accessed externally to joinlemmy's docker image. Its more reproducible and predictable that way. And it isn't difficult to do new deploys of joinlemmy to docker and do ansible deploys of `joinlemmy:latest` which will have the new instance stats.

> Also I think that the order of instances should be randomized. Otherwise the largest instances will always be on top and keep growing, while small instances are at the bottom and receive very few new users.

I'd much rather have popularity over randomness for now... most of the instances don't have much activity. Later on we should add some things to filter by, like joinmastodon has.

**Comment by Nutomic** [comment]
Okay I will add the blocklist feature, but then we have to remember to check the generated instance list after each run for any malicious instances.

**Comment by dessalines** [comment]
> Edit: Done. Note that if you pass --exclude, you will have to exclude ds9.lemmy.ml etc explicitly, or they will be crawled as well.

Nice, I'll add excluding the test instances, ping you there, then update this PR.

**Comment by Nutomic** [comment]
This ready now?

**Pull request merged**
