### PR TITLE
Add a section thanking contributors. Fixes #27

### LINKED ISSUE #27: Add a section thanking contributors
https://github.com/LemmyNet/lemmy-ui/issues/187

### PR DESCRIPTION
**Pull request by dessalines**

### CODE REVIEW

**Comment by Nutomic** [comment]
I still think it would be much better to show translators for your own language more prominently than translators for other languages. Also it would be nice if you included screenshots for design changes, so everyone can easily see what it means.

2021-03-25-100156_3146x1620_scrot

**Comment by dessalines** [comment]
Right now its:  image

What about bolding, and adding that first in the list, if its your language?

**Comment by Nutomic** [comment]
That could work. Also its a bit weird that code formatting is used for language names, maybe a table would work better? And `pt_BR` needs to be replaced with the actual language name.

**Comment by dessalines** [comment]
I'm kinda against a table here, because of the vertical space it would take up. But I can remove the code formatting on language. w/ respect to `pt_BR`, its unfortunately not an official language code: https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes , so the library I'm using doesn't know how to deal with it. But I can at least do the first part of it.

**Comment by Nutomic** [comment]
The country code comes from [ISO-3166](https://en.wikipedia.org/wiki/ISO_3166-1). I cant find the documentation for this, but its common to combine lang-country specifiers in this format to make it more specific, eg `en-US`, `de-DE`, `es-CU` and so on.

**Comment by dessalines** [comment]
I maybe found a library that can handle both, and do the unicode flags.

**Comment by dessalines** [comment]
image

**Comment by Nutomic** [comment]
Some strange parts in that screenshot:

- Why are there two translators named `T`? Seems wrong.
- Chinese, Korean, Japanese are not bold, probably cause the font doesnt support it. That messes up the whole layout and makes it hard to read. Maybe using a different text color would work better than bold?

Screenshot_20210329_210011

**Comment by dessalines** [comment]
> Why are there two translators named T? Seems wrong.

I checked the `translators.json`, that does seem to be the case. Might be the same person.

> Chinese, Korean, Japanese are not bold, probably cause the font doesnt support it. That messes up the whole layout and makes it hard to read. Maybe using a different text color would work better than bold?

I'll try that.

**Comment by dessalines** [comment]
How about this?

image

**Comment by Nutomic** [comment]
Just noticed that I attached the wrong screenshot above lol. Its consistent now, but a bit too colorful with green, red and white text. Not sure how to fix it though.

**Comment by dessalines** [comment]
Color is unfortunately probably the only way to do it, I'd prefer bold but not all languages support that.

**Pull request merged**
