### PR TITLE
Adding voyager patreon link.

### PR DESCRIPTION
**Pull request by dessalines**

### CODE REVIEW

**Comment by Nutomic** [comment]
Does this really belong on the site? None of the other apps have a donation link, and I think its enough if the link is available inside the app for those who use it.

**Comment by dessalines** [comment]
Yeah, there's no reason not to provide donation links if they want them. I'd also be open to adding donation links for sites also, if we ever add those.

**Comment by Nutomic** [comment]
Sure but I doubt that anyone would donate to an app after seeing it for the first time in this list. Plus how can the user be sure that the donation link is correct if its not coming directly from the app dev? 

For those reasons I think it makes much more sense to have each project directly show its donation links. Btw did the Voyager dev ask you to add this or was it your idea?

**Comment by dessalines** [comment]
My idea, I'd like to add donation info for any app or site that takes it.

**Comment by Nutomic** [comment]
Would be good if you can check with the Voyager dev if he likes this idea.

**Comment by dessalines** [comment]
aeharding did already.

**Review by Nutomic — APPROVED** [review]

**Comment by Nutomic** [comment]
Alright.

**Pull request merged**
