### PR TITLE
Updating API docs for user->person migration. Fixes #32

### LINKED ISSUE #32: Update API docs based on user -> person migration
Look at the recent `lemmy-js-client` PR for this.

### PR DESCRIPTION
**Pull request by dessalines**

### CODE REVIEW

**Review by Nutomic — APPROVED** [review]
Just had a quick look and it seems fine. Maybe @gazconroy has more to say.

**Comment by gazconroy** [comment]
Ditto. Seems fine. If asyncapi.html renders the asyncapi.yaml file, you've likely made all the right changes.

**Comment by dessalines** [comment]
Yep, I ran it to make sure that it rendered the changes, esp `my_user` and it seemed to fine. I don't know if there's any other type of checker for this specific asyncapi yaml.

**Comment by gazconroy** [comment]
That one is about as official as it gets...at this stage in AsyncAPI's lifecycle anyways

**Pull request merged**
