### PR TITLE
Add discuss.tchncs.de as a recommendation

### PR DESCRIPTION
**Pull request by sw1tchbl4d3r**

### CODE REVIEW

**Comment by verymilan** [comment]
oh, i was just preparing to do the pr – thanks, tho i think we could count as `en` as well :)

**Comment by sw1tchbl4d3r** [comment]
Nice to hear, and yeah, since the instance is bilingual that seems fair, I'll add it to en as well.

**Comment by Nutomic** [comment]
Actually sh.itjust.works was added for en and fr now, so we might as well list discuss.tchncs.de for de and en. So feel free to make another PR.

**Comment by verymilan** [comment]
Ah, thanks for the manual addition! 🤗

**Pull request merged**
